apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: b93sua5nw-nodejs 
  janus-idp.io/tekton: b93sua5nw-nodejs
  backstage.io/kubernetes-id: b93sua5nw-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: b93sua5nw-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml